name: Report Bug
description: "Report a bug that does not abruptly end a game session or prevent the start of the game."
labels: []
assignees: Roadhog360
body:
- type: markdown
  attributes:
    value: 'Thank you for opening a bug report! Please answer all required questions completely and accurately, and read the optional questions to see if they apply to your issue.
    If you\'d like to join our Discord server, you can find an invite link for that [here](https://discord.gg/jBHQn3Nmsh).
    If you want to suggest a change, please do not open an issue. Use the [discussions page](https://github.com/Roadhog360/Et-Futurum-Requiem/discussions) instead. Issues that are suggestions will be closed and locked.'

body:
- type: checkboxes
  id: initial
  attributes:
    label: checklist
    description: Please mark them so we can better handle this report
    options:
      - label: "I used a translator, such as Google Translate, to post this issue."
        required: false
      - label: "I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report."
        required: true
      - label: "I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like MCPC+, KCauldron, Crucible, Mohist etc"
        required: true
- type: markdown
  attributes:
    value: 'Please answer each question completely and to the best of your knowledge. Do not attempt to skip questions which are required.'
- type: input
  id: version
  attributes:
    label: Mod Version
    description: What version of the mod are you using? Give an actual version number or jar name, not "latest". Speaking of which, if you are not on the latest jar, try updating first. If you're using the nomixin jar, share that information please.
    placeholder: "2.6.0 snapshot+nomixin, and/or Et_Futurum_Requiem-2.6.0-SNAPSHOT-6f26e20e+nomixin.jar"
  validations:
    required: true
- type: textarea
  id: whatistheissue
  attributes:
    label: What is the issue?
    description: Describe the issue, as well as what you think the expected result should be.
    placeholder: "Example: 1 Foo is crafted but no Bar is consumed. 1 Bar should be consumed."
  validations:
    required: true
- type: textarea
  id: conflict
  attributes:
    label: Conflicting mods
    description: If this is a mod conflict, list the mods you think are causing the issue.
    placeholder: "Example: Causes <insert feature> to break only if <insert modname> is installed"
  validations:
    required: false
- type: input
  id: crash
  attributes:
    label: Crash Report
    description: If your issue is a crash, upload a link to the report here. Any paste website that does not require an account/password to view is fine, but GitHub Gists or https://rentry.co/ is preferred.
    placeholder: "https://rentry.co/example"
  validations:
    required: false
- type: textarea
  id: more
  attributes:
    label: Other details
    description: Additional details you think are important to provide, if it's a mod conflict, post the mods list here. If this is a worldgen issue, post seed, and coords here. Etc
    placeholder: "Insert logs, etc here."
  validations:
    required: false
